---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	validate_content(validate_content)
	validate_structure(validate_structure)
	validate_quiz(validate_quiz)
	calculate_readiness(calculate_readiness)
	generate_report(generate_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> validate_content;
	calculate_readiness --> generate_report;
	validate_content --> validate_structure;
	validate_quiz --> calculate_readiness;
	validate_structure --> validate_quiz;
	generate_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
